#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-globals
Version  : 0.12.3
Release  : 7
URL      : https://cran.r-project.org/src/contrib/globals_0.12.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/globals_0.12.3.tar.gz
Summary  : Identify Global Objects in R Expressions
Group    : Development/Tools
License  : LGPL-2.1
BuildRequires : buildreq-R

%description
by code inspection using various strategies, e.g. conservative or liberal.
    The objective of this package is to make it as simple as possible to
    identify global objects for the purpose of exporting them in distributed
    compute environments.

%prep
%setup -q -c -n globals

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537203046

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1537203046
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library globals
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library globals
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library globals
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library globals|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/globals/DESCRIPTION
/usr/lib64/R/library/globals/INDEX
/usr/lib64/R/library/globals/Meta/Rd.rds
/usr/lib64/R/library/globals/Meta/features.rds
/usr/lib64/R/library/globals/Meta/hsearch.rds
/usr/lib64/R/library/globals/Meta/links.rds
/usr/lib64/R/library/globals/Meta/nsInfo.rds
/usr/lib64/R/library/globals/Meta/package.rds
/usr/lib64/R/library/globals/NAMESPACE
/usr/lib64/R/library/globals/NEWS
/usr/lib64/R/library/globals/R/globals
/usr/lib64/R/library/globals/R/globals.rdb
/usr/lib64/R/library/globals/R/globals.rdx
/usr/lib64/R/library/globals/WORDLIST
/usr/lib64/R/library/globals/help/AnIndex
/usr/lib64/R/library/globals/help/aliases.rds
/usr/lib64/R/library/globals/help/globals.rdb
/usr/lib64/R/library/globals/help/globals.rdx
/usr/lib64/R/library/globals/help/paths.rds
/usr/lib64/R/library/globals/html/00Index.html
/usr/lib64/R/library/globals/html/R.css
